---
settings:
  name: ONTAP Automation
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de automação da ONTAP
    url: "/index.html"
  - title: O que há de novo
    entries:
    - title: Novidades com a API REST do ONTAP
      url: "/whats-new.html"
    - title: Alterações nas chamadas de API REST do ONTAP
      url: "/api-changes.html"
  - section: get-started
  - section: rest
  - section: workflows
  - section: sw-tools
  - section: migrate
  - section: reference
  - section: additional
  - title: Avisos legais
    url: "/legal-notices.html"
