---
sidebar: sidebar 
permalink: pstk/learn-about-pstk.html 
keywords: overview, powershell, powershell toolkit, install powershell toolkit 
summary: O NetApp fornece um kit de ferramentas para aplicativos do PowerShell que você pode usar para administrar seus sistemas de storage do ONTAP. O kit de ferramentas foi criado por desenvolvedores do NetApp e é suportado pela comunidade de clientes. 
---
= Saiba mais sobre o kit de ferramentas do NetApp PowerShell
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O NetApp fornece um kit de ferramentas para aplicativos do PowerShell que você pode usar para administrar seus sistemas de storage do ONTAP. O kit de ferramentas foi criado por desenvolvedores do NetApp e é suportado pela comunidade de clientes.



== Visão geral

O PowerShell é outra opção para automatizar a administração dos clusters do ONTAP.

.PowerShell
O PowerShell é uma linguagem de programação da Microsoft que você pode usar para automação de tarefas e gerenciamento de configuração. Ele inclui um ambiente shell de linha de comando, bem como uma linguagem de script.

.Kit de ferramentas do NetApp ONTAP
O kit de ferramentas do NetApp.ONTAP PowerShell inclui o módulo do PowerShell para NetApp ONTAP. O kit de ferramentas dá suporte ao ONTAP executado em vários ambientes, incluindo sistemas NetApp AFF e FAS, hardware comum e nuvem. O módulo inclui mais de 2.400 cmdlets que suportam coletivamente a administração de armazenamento em hosts Windows.



== Baixe e instale

Há duas opções disponíveis para baixar e instalar o kit de ferramentas do NetApp ONTAP PowerShell.

.Suporte à NetApp
Você pode baixar o kit de ferramentas do PowerShell do site de suporte da NetApp:

https://mysupport.netapp.com/site/tools/tool-eula/ontap-powershell-toolkit["Kit de ferramentas do NetApp.ONTAP"^]

.Galeria do PowerShell
Você pode baixar o kit de ferramentas do PowerShell da Galeria do PowerShell:

https://www.powershellgallery.com/packages/NetApp.ONTAP/["Kit de ferramentas do NetApp.ONTAP"^]
