---
sidebar: sidebar 
permalink: migrate/blogs_migrate.html 
keywords: blogs, blog articles 
summary: Existem vários artigos de blog disponíveis para ajudá-lo a entender melhor como migrar do ONTAPI para a API REST do ONTAP. 
---
= Artigos de blog
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Existem vários artigos de blog disponíveis para ajudá-lo a entender melhor como migrar do ONTAPI para a API REST do ONTAP.

.ONTAPI para mapeamento REST
O NetApp fornece suporte para passar da API patenteada ONTAPI para a API REST do ONTAP por meio de documentação de mapeamento.

https://netapp.io/2020/12/17/ontapi-to-rest-mapping/["NetApp.io/2020/12/17/ontapi-to-rest-mapping"^]

.Transforme sua automação em API REST do ONTAP com o ONTAPI
Há várias tecnologias disponíveis para ajudar você a transformar seu ambiente de automação do ONTAP com base na API REST.

https://www.netapp.com/blog/transform-automation-ontap-rest-api/["www.NetApp.com/blog/transform-automation-ONTAP-rest-api"^]

.Usando a passagem de CLI privada com a API REST do ONTAP
Para ajudar os usuários da CLI e do ONTAP a fazer a transição para a API REST do ONTAP, o ONTAP fornece um endpoint de API REST privado que pode ser usado para acessar qualquer comando da CLI.

https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api/["https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api"^]

.Transição do ONTAPI usando a ferramenta de relatórios de uso do ONTAPI
O NetApp fornece uma ferramenta para ajudar clientes e parceiros a fazer a transição para a API REST do ONTAP.

https://netapp.io/2022/03/21/transitioning-from-ontapizapi-using-ontapi-usage-reporting-tool/["NetApp.io/2022/03/21/transiting-from-ontapizapi-using-ontapi-use-reporting-tool"^]
