---
sidebar: sidebar 
permalink: additional/learn_more.html 
keywords: learn, learn more, more information, additional resources 
summary: Há vários recursos adicionais que você pode acessar para obter ajuda e encontrar mais informações sobre como automatizar a implantação e a administração de seus sistemas de storage ONTAP. 
---
= Saiba mais sobre a API REST do ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Há vários recursos adicionais disponíveis para ajudá-lo a automatizar a implantação e a administração de seus sistemas de storage ONTAP.



== Artigos de blog

Os artigos do blog são organizados em várias seções com base no assunto.



=== Geral

* Um bom resumo das tecnologias atuais de automação da ONTAP.
+
https://www.netapp.com/blog/new-normal-for-automation["Novo normal para automação"^]



* Você pode explorar usando a API REST do ONTAP para gerenciar a segurança e as permissões de arquivos.
+
https://netapp.io/2021/06/28/simplified-management-of-file-security-permissions-with-ontap-rest-apis["Gerenciamento simplificado de permissões de segurança de arquivos com APIs REST do ONTAP"^]

* Você pode monitorar eventos do ONTAP para se manter ciente da atividade do sistema. A configuração e o gerenciamento desses eventos podem ser automatizados usando a API REST.
+
https://blog.netapp.com/ontap-rest-apis-automate-notification["APIS REST do ONTAP: Automatize a notificação de eventos de alta gravidade"^]

* Você pode usar a API REST para configurar funções e níveis de acesso como parte de um ambiente de segurança RBAC.
+
https://netapp.io/2022/06/26/rbac-using-ontap-rest-apis["Controle de acesso baseado em função (RBAC) usando APIS REST do ONTAP"^]

* Coffee breaks with REST (6 episódios):
+
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-1-Basics-of-ONTAP-REST-APIs/m-p/167852["Noções básicas das APIs REST do ONTAP"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-2-Features-of-ONTAP-REST-APIs/m-p/168168/highlight/true#M208["Recursos das APIS REST do ONTAP"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-3-Getting-Hands-on-with-ONTAP-REST-using-Postman/m-p/431965/highlight/true#M283["Fazer hands-on com ONTAP REST usando Postman"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-4-ONTAPI-ZAPI-Reporting-tool/m-p/433200["Ferramenta de relatórios ONTAPI (ZAPI)"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-5-Private-CLI-Passthrough/m-p/435293["Passagem de CLI privada"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-6-5-magical-features-that-make-ONTAP-storage/m-p/435604["5 recursos mágicos que tornam a automação de armazenamento ONTAP simples!"^]






=== Biblioteca cliente Python

* Uma introdução ao uso dos scripts de exemplo Python que o NetApp fornece no GitHub para acessar a API REST do ONTAP.
+
https://netapp.io/2020/04/23/ontap-rest-apis["Os scripts de exemplo de Python da API REST do ONTAP agora estão disponíveis no GitHub!"^]

* Este blog fornece uma boa introdução aos recursos da biblioteca cliente do ONTAP Python.
+
https://www.netapp.com/blog/simplify-ontap-rest-api-consumption["Simplifique o consumo de API REST do ONTAP com a biblioteca de clientes Python"^]

* Esta é uma série de blogs de três partes sobre como começar a usar a biblioteca cliente Python:
+
** https://netapp.io/2020/06/09/ontap-rest-api-python-client-library-pt1["Parte 1"^]
** https://netapp.io/2020/06/09/ontap-rest-api-python-client-library-pt2["Parte 2"^]
** https://netapp.io/2020/06/09/ontap-rest-api-python-client-library-pt3["Parte 3"^]






=== Migração para a API REST

* O NetApp fornece suporte para passar da API patenteada ONTAPI para a API REST do ONTAP por meio de documentação de mapeamento.
+
https://netapp.io/2020/12/17/ontapi-to-rest-mapping/["ONTAPI para mapeamento REST"^]

* Há várias tecnologias disponíveis para ajudar você a transformar seu ambiente de automação do ONTAP com base na API REST.
+
https://www.netapp.com/blog/transform-automation-ontap-rest-api/["Transforme sua automação em API REST do ONTAP com o ONTAPI"^]

* Para ajudar os usuários da CLI e do ONTAP a fazer a transição para a API REST do ONTAP, o ONTAP fornece um endpoint de API REST privado que pode ser usado para acessar qualquer comando da CLI.
+
https://netapp.io/2020/11/09/private-cli-passthrough-ontap-rest-api/["Usando a passagem de CLI privada com a API REST do ONTAP"^]

* O NetApp fornece uma ferramenta para ajudar clientes e parceiros a fazer a transição para a API REST do ONTAP.
+
https://netapp.io/2022/03/21/transitioning-from-ontapizapi-using-ontapi-usage-reporting-tool/["Transição do ONTAPI (ZAPI) usando a ferramenta de relatórios de uso do ONTAPI"^]





== Vídeos

* Uma boa introdução à biblioteca cliente Python do NetApp e como começar a escrever código usando a biblioteca.
+
video::pg5ls1Ol6uw[youtube,width=848,height=480]
* Veja os módulos certificados Ansible.
+
video::ZlmQ5IuVZD8[youtube,width=848,height=480]
+
video::L5DZBV_Sg9E[youtube,width=848,height=480]
* Uma coleção de vídeos na NetApp TechComm TV.
+
https://www.youtube.com/playlist?list=PLHSh2r3A9gQRG1kkAcx1MmtVYPimyxOp_["Automatize o gerenciamento de NetApp ONTAP"^]





== Base de dados de Conhecimento da NetApp

* Se você encontrar um problema com a API REST do ONTAP, poderá denunciá-lo ao NetApp.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_report_REST_API_and_NetApp_Python_Module_(REST_API_via_python_module)_issues["Como relatar problemas na API REST do ONTAP e na biblioteca de clientes Python da API REST do ONTAP"^]

* Se você identificar uma lacuna funcional na API REST do ONTAP, poderá solicitar um novo recurso para a API.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_request_a_feature_for_ONTAP_REST_API["Como solicitar um recurso para a API REST do ONTAP"^]


