---
sidebar: sidebar 
permalink: additional/learn_more.html 
keywords: learn, learn more, more information, additional resources 
summary: Há vários recursos adicionais que você pode acessar para obter ajuda e encontrar mais informações sobre como automatizar a implantação e a administração de seus sistemas de storage ONTAP. 
---
= Saiba mais sobre a API REST do ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Há vários recursos adicionais disponíveis para ajudá-lo a automatizar a implantação e a administração de seus sistemas de storage ONTAP.



== Artigos de blog

Os artigos do blog são organizados em várias seções com base no assunto.



=== Geral

* Um bom resumo das tecnologias atuais de automação da ONTAP.
+
https://www.netapp.com/blog/new-normal-for-automation["Novo normal para automação"^]

* Você pode monitorar eventos do ONTAP para se manter ciente da atividade do sistema. A configuração e o gerenciamento desses eventos podem ser automatizados usando a API REST.
+
https://blog.netapp.com/ontap-rest-apis-automate-notification["APIS REST do ONTAP: Automatize a notificação de eventos de alta gravidade"^]

* Coffee breaks with REST (6 episódios):
+
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-1-Basics-of-ONTAP-REST-APIs/m-p/167852["Noções básicas das APIs REST do ONTAP"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-2-Features-of-ONTAP-REST-APIs/m-p/168168/highlight/true#M208["Recursos das APIS REST do ONTAP"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-3-Getting-Hands-on-with-ONTAP-REST-using-Postman/m-p/431965/highlight/true#M283["Fazer hands-on com ONTAP REST usando Postman"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-4-ONTAPI-ZAPI-Reporting-tool/m-p/433200["Ferramenta de relatórios ONTAPI (ZAPI)"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-5-Private-CLI-Passthrough/m-p/435293["Passagem de CLI privada"^]
** https://community.netapp.com/t5/ONTAP-Rest-API-Discussions/Coffee-breaks-with-REST-Episode-6-5-magical-features-that-make-ONTAP-storage/m-p/435604["5 recursos mágicos que tornam a automação de armazenamento ONTAP simples!"^]






=== Biblioteca cliente Python

* Este blog fornece uma boa introdução aos recursos da biblioteca cliente do ONTAP Python.
+
https://www.netapp.com/blog/simplify-ontap-rest-api-consumption["Simplifique o consumo de API REST do ONTAP com a biblioteca de clientes Python"^]





=== Migração para a API REST

* Há várias tecnologias disponíveis para ajudar você a transformar seu ambiente de automação do ONTAP com base na API REST.
+
https://www.netapp.com/blog/transform-automation-ontap-rest-api/["Transforme sua automação em API REST do ONTAP com o ONTAPI"^]





== Vídeos

* Uma boa introdução à biblioteca cliente Python do NetApp e como começar a escrever código usando a biblioteca.
+
video::pg5ls1Ol6uw[youtube,width=848,height=480]
* Veja os módulos certificados Ansible.
+
video::ZlmQ5IuVZD8[youtube,width=848,height=480]
+
video::L5DZBV_Sg9E[youtube,width=848,height=480]
* Uma coleção de vídeos na NetApp TechComm TV.
+
https://www.youtube.com/playlist?list=PLHSh2r3A9gQRG1kkAcx1MmtVYPimyxOp_["Automatize o gerenciamento de NetApp ONTAP"^]





== Base de dados de Conhecimento da NetApp

* Se você encontrar um problema com a API REST do ONTAP, poderá denunciá-lo ao NetApp.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_report_REST_API_and_NetApp_Python_Module_(REST_API_via_python_module)_issues["Como relatar problemas na API REST do ONTAP e na biblioteca de clientes Python da API REST do ONTAP"^]

* Se você identificar uma lacuna funcional na API REST do ONTAP, poderá solicitar um novo recurso para a API.
+
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_request_a_feature_for_ONTAP_REST_API["Como solicitar um recurso para a API REST do ONTAP"^]


