---
sidebar: sidebar 
permalink: sw-tools/learn-about-nmsdk.html 
keywords: netapp manageability sdk, oncommand workflow automation, oncommand wfa, ontapi, zapi 
summary: O SDK de gerenciamento do NetApp fornece um conjunto de chamadas de API do ONTAPI para desenvolver aplicativos para monitorar e gerenciar seu storage do ONTAP. Juntamente com o pacote OnCommand Workflow Automation, o SDK apoia seus esforços para automatizar o gerenciamento de seus sistemas ONTAP. 
---
= Saiba mais sobre o SDK de gerenciamento do NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O SDK de gerenciamento do NetApp fornece um conjunto de chamadas de API do ONTAPI para desenvolver aplicativos para monitorar e gerenciar seu storage do ONTAP. Juntamente com o pacote OnCommand Workflow Automation, o SDK apoia seus esforços para automatizar o gerenciamento de seus sistemas ONTAP.


NOTE: Embora o NetApp Manageability SDK e o OnCommand Workflow Automation continuem a ser suportados, a ONTAP REST API é a tecnologia preferencial e estratégica para usar ao automatizar seus sistemas ONTAP . Ver link:../migrate/migration-considerations.html["Migre da ONTAPI para a API REST"] para maiores informações.

.Faça o download do SDK
Você pode baixar o SDK de gerenciamento do NetApp a partir do site de suporte da NetApp. O SDK suporta várias linguagens do lado do cliente, incluindo: Python, PowerShell, C, Java, C, VB.Net e Ruby. Certifique-se de revisar a ferramenta Matriz de interoperabilidade para obter informações sobre o SDK de gerenciamento do NetApp e como ele é suportado com sua versão do ONTAP.

.Use o OnCommand Workflow Automation
Você também pode usar a API fornecida com o SDK para automatizar tarefas de gerenciamento sem escrever nenhum script. O OnCommand Workflow Automation (OnCommand WFA) fornece vários fluxos de trabalho pré-empacotados para implantar e executar as tarefas de gerenciamento.

.Informações relacionadas
* https://mysupport.netapp.com/site/["Site de suporte da NetApp"^]
* https://www.netapp.com/company/interoperability/["Ferramenta de Matriz de interoperabilidade do NetApp"^]
* https://mysupport.netapp.com/documentation/docweb/index.html?productID=63638&language=en-US["Documentação do SDK de gerenciabilidade do NetApp"^]
* https://docs.netapp.com/us-en/workflow-automation/["Documentação do OnCommand Workflow Automation"^]

