---
sidebar: sidebar 
permalink: workflows/wf_cls_update_contact.html 
keywords: workflow, update cluster, cluster contact 
summary: Pode atualizar as informações de contacto de um cluster. Como a solicitação é processada de forma assíncrona, você também precisa determinar se a tarefa em segundo plano associada foi concluída com êxito. 
---
= Atualize o Contato do cluster usando a API REST do ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pode atualizar as informações de contacto de um cluster. Como a solicitação é processada de forma assíncrona, você também precisa determinar se a tarefa em segundo plano associada foi concluída com êxito.



== Passo 1: Atualize as informações de contacto do cluster

Você pode emitir uma chamada de API para atualizar as informações de Contato do cluster.

.Método HTTP e endpoint
Essa chamada de API REST usa o método e o endpoint a seguir.

[cols="25,75"]
|===
| Método HTTP | Caminho 


| PATCH | /api/cluster 
|===
.Tipo de processamento
Assíncrono

.Curl exemplo
[source, curl]
----
curl --request PATCH \
--location "https://$FQDN_IP/api/cluster" \
--include \
--header "Content-Type: application/json" \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH" \
--data @JSONinput
----
.Exemplo de entrada JSON
[source, json]
----
{
  "contact": "support@company-demo.com"
}
----
.Exemplo de saída JSON
Um objeto de tarefa é retornado. Você deve salvar o identificador do trabalho para usá-lo na próxima etapa.

[listing]
----
{ "job": {
    "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
      }
    }
  }
}
----


== Passo 2: Recupere o status do trabalho

Execute o fluxo de trabalho link:../workflows/wf_jobs_get_job.html["Obter instância de trabalho"] e confirme se `state` o valor é `success`.



== Passo 3: Confirme as informações de contacto do cluster

Execute o fluxo de link:../workflows/wf_cls_get_cluster.html["Obtenha a configuração do cluster"]trabalho . Você deve definir o `fields` parâmetro de consulta como `contact`.
