---
sidebar: sidebar 
permalink: workflows/wf_ems_list_log_events.html 
keywords: support, ems, event management system, get events, get notifications, retrieve events 
summary: Você pode recuperar todas as mensagens de notificação de eventos ou aquelas com caraterísticas específicas. 
---
= Listar os eventos de log do EMS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode recuperar todas as mensagens de notificação de eventos ou apenas aquelas com caraterísticas específicas.

.Método HTTP e endpoint
Essa chamada de API REST usa o método e o endpoint a seguir.

[cols="25,75"]
|===
| Método HTTP | Caminho 


| OBTER | /api/support/ems/events 
|===
.Tipo de processamento
Síncrono

.Parâmetros de entrada adicionais para os exemplos Curl
Além dos parâmetros comuns com todas as chamadas de API REST, os seguintes parâmetros também são usados nos exemplos curl para esta etapa.

[cols="25,10,10,55"]
|===
| Parâmetro | Tipo | Obrigatório | Descrição 


| campos | Consulta | Não | Usado para solicitar campos específicos para serem incluídos na resposta. 


| max_records | Consulta | Não | Pode ser usado para limitar o número de Registros retornados em uma única solicitação. 


| log_message | Consulta | Não | Usado para pesquisar um valor de texto específico e retornar apenas as mensagens correspondentes. 


| message.severity | Consulta | Não | Limite as mensagens retornadas para aquelas com uma gravidade específica, `alert` como . 
|===
.Curl exemplo: Retorna a mensagem mais recente e o valor do nome
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/support/ems/events?fields=message.name&max_records=1" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Curl exemplo: Retorna uma mensagem contendo texto e gravidade específicos
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/support/ems/events?log_message=*disk*&message.severity=alert" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Exemplo de saída JSON
[listing]
----
{
  "records": [
    {
      "node": {
        "name": "malha-vsim1",
        "uuid": "da4f9e62-9de3-11ec-976a-005056b369de",
        "_links": {
          "self": {
            "href": "/api/cluster/nodes/da4f9e62-9de3-11ec-976a-005056b369de"
          }
        }
      },
      "index": 4602,
      "time": "2022-03-18T06:37:46-04:00",
      "message": {
        "severity": "alert",
        "name": "raid.autoPart.disabled"
      },
      "log_message": "raid.autoPart.disabled: Disk auto-partitioning is disabled on this system: the system needs a minimum of 4 usable internal hard disks.",
      "_links": {
        "self": {
          "href": "/api/support/ems/events/malha-vsim1/4602"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/support/ems/events?log_message=*disk*&message.severity=alert&max_records=1"
    },
    "next": {
      "href": "/api/support/ems/events?start.keytime=2022-03-18T06%3A37%3A46-04%3A00&start.node.name=malha-vsim1&start.index=4602&log_message=*disk*&message.severity=alert"
    }
  }
}
----