---
sidebar: sidebar 
permalink: workflows/wf_jobs_get_job.html 
keywords: workflow, job, job state 
summary: Você pode recuperar a instância de um trabalho ONTAP específico. Normalmente, você faria isso para determinar se o trabalho e a operação associada foram concluídos com êxito. 
---
= Obter instância de tarefa usando a API REST do ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode recuperar a instância de um trabalho ONTAP específico. Normalmente, você faria isso para determinar se o trabalho e a operação associada foram concluídos com êxito.


NOTE: Você precisa do UUID do objeto de tarefa, que normalmente é fornecido após a emissão de uma solicitação assíncrona. Reveja também link:../rest/asynchronous_processing.html["Processamento assíncrono usando o objeto Job"]antes de trabalhar com trabalhos internos do ONTAP.

.Método HTTP e endpoint
Essa chamada de API REST usa o método e o endpoint a seguir.

[cols="25,75"]
|===
| Método HTTP | Caminho 


| OBTER | /api/cluster/jobs/(uuuid) 
|===
.Tipo de processamento
Síncrono

.Parâmetros de entrada adicionais para os exemplos Curl
Além dos parâmetros comuns com todas as chamadas de API REST, os seguintes parâmetros também são usados nos exemplos curl para esta etapa.

[cols="25,10,10,55"]
|===
| Parâmetro | Tipo | Obrigatório | Descrição 


| JOB_ID | Caminho | Sim | Necessário para identificar o trabalho que está a ser solicitado. 
|===
.Curl exemplo
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP/api/cluster/jobs/$JOB_ID" \
--include \
--header "Accept: */*" \
--header "Authorization: Basic $BASIC_AUTH"
----
.Exemplo de saída JSON
O valor do estado e outros campos são incluídos no objeto de trabalho retornado. A tarefa neste exemplo foi executada como parte da atualização de um cluster ONTAP.

[listing]
----
{
  "uuid": "d877f5bb-3aa7-11e9-b6c6-005056a78c89",
  "description": "PATCH /api/cluster",
  "state": "success",
  "message": "success",
  "code": 0,
  "_links": {
    "self": {
      "href": "/api/cluster/jobs/d877f5bb-3aa7-11e9-b6c6-005056a78c89"
    }
  }
}
----