---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_delete_ace.html 
keywords: nas, file security, access control entry, ace, delete ace 
summary: 'Você pode excluir uma entrada de controle de acesso existente (ACE) de um arquivo ou pasta específico. A mudança se propaga para quaisquer objetos filho.' 
---
= Eliminar uma entrada de controlo de acesso
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode excluir uma entrada de controle de acesso (ACE) existente de um arquivo ou pasta específico. A mudança se propaga para quaisquer objetos filho.



== Passo 1: Exclua o ACE

.Método HTTP e endpoint
Essa chamada de API REST usa o método e o endpoint a seguir.

[cols="25,75"]
|===
| Método HTTP | Caminho 


| ELIMINAR | /api/protocols/file-security/permissions/(caminho) 
|===
.Tipo de processamento
Assíncrono

.Parâmetros de entrada adicionais para exemplos curl
Além dos parâmetros comuns com todas as chamadas de API REST, os seguintes parâmetros também são usados no exemplo curl nesta etapa.

[cols="25,10,10,55"]
|===
| Parâmetro | Tipo | Obrigatório | Descrição 


| SVM_ID | Caminho | Sim | Este é o UUID do SVM que contém o arquivo. 


| FILE_PATH | Caminho | Sim | Este é o caminho para o arquivo ou pasta. 
|===
.Curl exemplo
[source, curl]
----
curl --request DELETE --location "https://$FQDN_IP/api/protocols/file-security/permissions/$SVM_ID/$FILE_PATH?return_timeout=0" --include --header "Accept */*" --header "Authorization: Basic $BASIC_AUTH" --data '{ \"access\": \"access_allow\", \"apply_to\": { \"files\": true, \"sub_folders\": true, \"this_folder\": true }, \"ignore_paths\": [ \"/parent/child2\" ], \"propagation_mode\": \"propagate\"}'
----
.Exemplo de saída JSON
[listing]
----
{
  "job": {
    "uuid": "3015c294-5bbc-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/3015c294-5bbc-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Passo 2: Recupere o status do trabalho

Execute o fluxo de trabalho link:../workflows/wf_jobs_get_job.html["Obter instância de trabalho"] e confirme se `state` o valor é `success`.
