---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_prepare.html 
keywords: nas, file security, sacl, dacl, prepare 
summary: Você pode gerenciar as permissões e as políticas de auditoria de arquivos disponíveis nos SVMs em um cluster do ONTAP. 
---
= Prepare-se para gerenciar políticas de auditoria e segurança de arquivos usando a API REST do ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode gerenciar as permissões e as políticas de auditoria de arquivos disponíveis nos SVMs em um cluster do ONTAP.



[[overview]]
=== Visão geral

O ONTAP usa listas de controle de acesso do sistema (SACLs) e listas de controle de acesso discricionárias (DACLs) para atribuir permissões a objetos de arquivo. A partir do ONTAP 9.9,1, a API REST inclui suporte para gerenciar as permissões SACL e DACL. Você pode usar a API para automatizar a administração das permissões de segurança de arquivos. Em muitos casos, você pode usar uma única chamada de API REST em vez de vários comandos CLI ou chamadas ONTAPI (ZAPI).


NOTE: Para versões do ONTAP anteriores à 9.9.1, você pode automatizar a administração das permissões SACL e DACL usando o recurso de passagem direta da CLI. Consulte link:../migrate/migration-considerations.html["Considerações sobre migração"] para mais informações.

Vários fluxos de trabalho de exemplo estão disponíveis para ilustrar como gerenciar os serviços de segurança de arquivos do ONTAP usando a API REST. Antes de usar os fluxos de trabalho e emitir qualquer uma das chamadas de API REST, verifique link:../workflows/prepare_workflows.html["Prepare-se para usar os fluxos de trabalho"]o .

Se você usar Python, consulte também o script https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/file_security_permissions.py["file_security_permissions.py"^] para obter exemplos de como automatizar algumas das atividades de segurança de arquivos.



[[ontap-rest-api-versus-ontap-cli-commands]]
=== API REST do ONTAP versus comandos CLI do ONTAP

Para muitas tarefas, o uso da API REST do ONTAP requer menos chamadas do que as chamadas equivalentes de comandos CLI do ONTAP ou de ONTAPI (ZAPI). A tabela abaixo inclui uma lista de chamadas de API e o equivalente aos comandos CLI necessários para cada tarefa.

[cols="40,60"]
|===
| API REST do ONTAP | CLI do ONTAP 


| `GET /protocols/file-security/effective-permissions/`  a| 
`vserver security file-directory show-effective-permissions`



| `POST /protocols/file-security/permissions/`  a| 
. `vserver security file-directory ntfs create`
. `vserver security file-directory ntfs dacl add`
. `vserver security file-directory ntfs sacl add`
. `vserver security file-directory policy create`
. `vserver security file-directory policy task add`
. `vserver security file-directory apply`




| `PATCH /protocols/file-security/permissions/`  a| 
`vserver security file-directory ntfs modify`



| `DELETE /protocols/file-security/permissions/`  a| 
. `vserver security file-directory ntfs dacl remove`
. `vserver security file-directory ntfs sacl remove`


|===
.Informações relacionadas
* https://github.com/NetApp/ontap-rest-python/blob/master/examples/rest_api/file_security_permissions.py["Script Python ilustrando permissões de arquivos"^]

