---
sidebar: sidebar 
permalink: workflows/wf_nas_fs_update_sd.html 
keywords: nas, file security, security descriptor, sd, update security descriptor 
summary: Você pode atualizar um descritor de segurança específico para um arquivo ou pasta específico, incluindo os sinalizadores principal do proprietário, grupo ou controle. 
---
= Atualize as informações do descritor de segurança
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode atualizar um descritor de segurança específico para um arquivo ou pasta específico, incluindo os sinalizadores principal do proprietário, grupo ou controle.



== Etapa 1: Atualize o descritor de segurança

.Método HTTP e endpoint
Essa chamada de API REST usa o método e o endpoint a seguir.

[cols="25,75"]
|===
| Método HTTP | Caminho 


| PATCH | /api/protocols/file-security/permissions/(caminho) 
|===
.Tipo de processamento
Assíncrono

.Parâmetros de entrada adicionais para exemplos curl
Além dos parâmetros comuns com todas as chamadas de API REST, os seguintes parâmetros também são usados no exemplo curl nesta etapa.

[cols="25,10,10,55"]
|===
| Parâmetro | Tipo | Obrigatório | Descrição 


| SVM_ID | Caminho | Sim | Este é o UUID do SVM que contém o arquivo. 


| FILE_PATH | Caminho | Sim | Este é o caminho para o arquivo ou pasta. 
|===
.Curl exemplo
[source, curl]
----
curl --request POST --location "https://$FQDN_IP/api/protocols/file-security/permissions/$SVM_ID/$FILE_PATH?return_timeout=0" --include --header "Accept */*" --header "Authorization: Basic $BASIC_AUTH" --data '{ \"control_flags\": \"32788\", \"group\": \"everyone\", \"owner\": \"user1\"}'
----
.Exemplo de saída JSON
[listing]
----
{
  "job": {
    "uuid": "6f89e612-5bbd-11eb-9c4e-0050568e8682",
    "_links": {
      "self": {
        "href": "/api/cluster/jobs/6f89e612-5bbd-11eb-9c4e-0050568e8682"
      }
    }
  }
}
----


== Passo 2: Recupere o status do trabalho

Execute o fluxo de trabalho link:../workflows/wf_jobs_get_job.html["Obter instância de trabalho"] e confirme se `state` o valor é `success`.
