---
sidebar: sidebar 
permalink: workflows/wf_rbac_prepare.html 
keywords: security, rbac, prepare rbac, rbac workflows 
summary: Você pode usar a funcionalidade RBAC do ONTAP de várias maneiras diferentes, dependendo do seu ambiente. Alguns cenários comuns são apresentados como fluxos de trabalho nesta seção. Em cada caso, o foco está em um objetivo específico de segurança e administração. 
---
= Prepare-se para usar o RBAC
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode usar a funcionalidade RBAC do ONTAP de várias maneiras diferentes, dependendo do seu ambiente. Alguns cenários comuns são apresentados como fluxos de trabalho nesta seção. Em cada caso, o foco está em um objetivo específico de segurança e administração.

Antes de criar quaisquer funções e atribuir uma função a uma conta de usuário do ONTAP, você deve se preparar revisando os principais requisitos e opções de segurança apresentados abaixo. Certifique-se também de rever os conceitos gerais do fluxo de trabalho em link:../workflows/prepare_workflows.html["Prepare-se para usar os fluxos de trabalho"].

.Qual versão do ONTAP você está usando?
A versão do ONTAP determina quais endpoints REST e recursos RBAC estão disponíveis.

.Identificar os recursos e o escopo protegidos
Você precisa identificar os recursos ou comandos a serem protegidos e o escopo (cluster ou SVM).

.Que acesso o usuário deve ter?
Depois de identificar os recursos e o escopo, você precisa determinar o nível de acesso a ser concedido.

.Como os usuários acessarão o ONTAP?
O usuário pode acessar o ONTAP por meio da API REST ou CLI ou ambos.

.Uma das funções incorporadas é suficiente ou é necessária uma função personalizada?
É mais conveniente usar uma função integrada existente, mas você pode criar uma nova função personalizada, se necessário.

.Que tipo de papel é necessário?
Com base nos requisitos de segurança e no acesso à ONTAP, você precisa escolher se deseja criar uma FUNÇÃO REST ou tradicional.
