---
sidebar: sidebar 
permalink: python/overview_pcl.html 
keywords: overview, python client library, pcl 
summary: A biblioteca cliente NetApp ONTAP Python é um pacote que você pode instalar e usar para escrever scripts que acessam a API REST do ONTAP. Usando a biblioteca cliente Python, você pode desenvolver rapidamente código robusto para suportar a automação de implantações ONTAP. 
---
= Visão geral da biblioteca cliente Python
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A biblioteca cliente NetApp ONTAP Python é um pacote que você pode instalar e usar para escrever scripts que acessam a API REST do ONTAP. Ele fornece suporte para vários serviços subjacentes, incluindo gerenciamento de conexão, processamento assíncrono, tratamento de exceções e mensagens de erro. Usando a biblioteca cliente Python, você pode desenvolver rapidamente código robusto para suportar a automação de implantações ONTAP.


NOTE: O NetApp mantém um repositório do GitHub contendo amostras de código e outras informações úteis. Você pode navegar para a pasta _examples_ para acessar amostras usando a biblioteca cliente Python.

.Informações relacionadas
* https://github.com/NetApp/ontap-rest-python["Repositório REST do ONTAP Python"^]
* https://github.com/NetApp/ontap-rest-python/tree/master/examples/python_client_library["Exemplos de Biblioteca de Cliente Python REST do ONTAP"^]

