---
sidebar: sidebar 
permalink: python/prepare_pcl.html 
keywords: python client library, prepare, pcl 
summary: Você deve preparar o ambiente de tempo de execução local antes de usar a biblioteca cliente Python. 
---
= Prepare-se para usar a biblioteca cliente Python
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você deve preparar o ambiente de tempo de execução local antes de usar a biblioteca cliente Python.

.Nome e versão do pacote
O nome do pacote de biblioteca cliente Python é *NetApp-ONTAP*. A versão associada ao pacote é uma combinação dos números de versão maior e menor do ONTAP a partir da qual a biblioteca foi gerada, juntamente com uma versão menor para o cliente dentro da versão do ONTAP. Por exemplo, os números de versão válidos incluem: 9,6.1, 9,6.2 e 9,7.1.

.Instalação
Você deve usar o pip para instalar o pacote NetApp_ONTAP a partir do site PyPi (Python Package Index).

.Pacotes e documentação da versão ONTAP
Cada versão do ONTAP que começa com 9,6 tem um pacote PyPI e documentação associada. Consulte link:../python/packages.html["Pacotes e documentação"] para obter mais informações. Os requisitos de instalação são incluídos em cada pacote e incluem diferentes versões do seguinte:

* python
* pedidos
* pedidos-cinto de ferramentas
* marshmallow

