---
sidebar: sidebar 
permalink: get-started/access_rest_api.html 
keywords: access rest api, lif, cluster lif, svm lif, node lif 
summary: Você pode acessar a API REST do ONTAP de várias maneiras diferentes. 
---
= Como acessar a API REST do ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Você pode acessar a API REST do ONTAP de várias maneiras diferentes.



== Considerações de rede

Você pode se conectar à API REST do ONTAP usando um dos vários tipos de interfaces disponíveis. A LIF escolhida precisa ser configurada para suportar o protocolo de gerenciamento HTTPS. Além disso, a configuração do firewall em sua rede deve permitir o tráfego HTTPS. As seguintes interfaces são suportadas:

* LIF de gerenciamento de clusters
* LIF de gerenciamento de nós
* LIF de gerenciamento do SVM


Embora você possa usar qualquer uma dessas LIFs, a prática recomendada é usar a LIF de gerenciamento de cluster. Isso permite que o cluster seja endereçado como uma única unidade lógica e proporciona o mais alto nível de resiliência e balanceamento de carga. Uma LIF de cluster pode ser realocada dentro do cluster conforme necessário para lidar com atualizações planejadas, eventos de quorum e outros problemas de conectividade. Se você tiver várias LIFs de gerenciamento de cluster configuradas, todas elas serão equivalentes em relação ao acesso à API REST. Os LIFs de gerenciamento do SVM também possuem balanceamento de carga, mas as solicitações enviadas para LIFs com escopo em nível de nó são tratadas localmente.



== Página de documentação online da API ONTAP

A página de documentação on-line da API do ONTAP fornece um ponto de acesso ao usar um navegador da Web. Além de fornecer uma maneira de executar chamadas individuais de API diretamente, a página inclui uma descrição detalhada da API, incluindo parâmetros de entrada e outras opções para cada chamada. As chamadas de API são organizadas em categorias funcionais. Consulte link:../resources/overview_categories.html["Resumo dos recursos REST"] para obter mais informações.

O formato do URL usado para acessar a página de documentação para a versão mais recente da API é:

`\https://<cluster_mgmt_ip_address>/docs/api`



== Software e ferramentas personalizadas

Você pode acessar a API do ONTAP usando qualquer uma das várias linguagens e ferramentas de programação diferentes. As opções populares incluem Python, Java, Curl e PowerShell. Um programa, script ou ferramenta que usa a API atua como um cliente de serviços da Web REST. O uso de uma linguagem de programação permite uma compreensão mais profunda da API e oferece uma oportunidade para automatizar a administração do ONTAP.

O formato da URL base usada para acessar diretamente a versão mais recente da API é:

`\https://<cluster_mgmt_ip_address>/api`

Para acessar uma versão específica da API em que várias versões são suportadas, o formato da URL é:

`\https://<cluster_mgmt_ip_address>/api/v1`
