---
sidebar: sidebar 
permalink: get-started/ontap_automation_options.html 
keywords: ontap automation, rest api, python client library, powershell, ansible, bluexp automation catalog, netapp, console, hub 
summary: Há várias opções disponíveis para automatizar a implantação e a administração dos sistemas de storage da ONTAP. 
---
= Entenda as opções de automação do ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Há várias opções disponíveis para automatizar a implantação e a administração dos sistemas de storage da ONTAP.



== API REST do ONTAP

A partir do ONTAP 9.6, o ONTAP inclui uma API REST robusta que fornece a base para automatizar a implantação e a administração dos seus sistemas de armazenamento.  Desde então, a API REST continuou a se expandir e amadurecer.  Agora ele fornece a opção preferencial e estratégica ao automatizar a administração de suas implantações ONTAP .

.Acessando a API REST nativamente
Você pode acessar a API REST do ONTAP diretamente usando qualquer linguagem de programação compatível com um CLIENTE REST. As opções de linguagem populares incluem Python, PowerShell e Java.

.Migrando código legacy ONTAPI para usar REST
A API ONTAPI (Zephyr API ou ZAPI) é o conjunto original de chamadas proprietárias incluído no software NetApp ONTAP para dar suporte à automação de suas tarefas de administração e gerenciamento de armazenamento de dados.  A API faz parte dolink:../sw-tools/learn-about-nmsdk.html["SDK de gerenciamento do NetApp"] .  Se você tiver código existente usando a API ONTAPI, planeje sua migração para a API REST ONTAP para aproveitar o conjunto de recursos expandido disponível com a API REST.  A NetApp fornece suporte para converter seu código para usar a API REST ONTAP mais recente. Ver link:../migrate/migration-considerations.html["Migre da ONTAPI para a API REST"] para maiores informações.



== Kits de ferramentas de software cliente

O NetApp fornece kits de ferramentas do cliente que abstraem a API REST do ONTAP e facilitam a criação de código de automação. Você deve escolher um apropriado para sua linguagem de desenvolvimento e ambiente.

.Biblioteca cliente Python
A biblioteca cliente Python é um pacote que você pode usar ao escrever scripts para acessar a API REST do ONTAP. Ele fornece suporte para vários serviços subjacentes, incluindo gerenciamento de conexão, processamento de solicitações assíncronas e tratamento de exceções. Ao usar a biblioteca cliente Python, você pode desenvolver rapidamente um código robusto para dar suporte aos seus objetivos de automação do ONTAP. Consulte link:../python/learn-about-pcl.html["Biblioteca cliente Python"] para obter mais informações.

.Kit de ferramentas do PowerShell
Você pode usar o kit de ferramentas do NetApp.ONTAP PowerShell para automatizar a administração de um cluster do ONTAP a partir de um host do Windows. Consulte link:../pstk/learn-about-pstk.html["Saiba mais sobre o kit de ferramentas do NetApp PowerShell"] para obter mais informações.



== Estruturas de automação

Você pode criar e implantar código de automação usando uma das várias estruturas.

.Ansible
O Ansible é uma ferramenta de software de código aberto compatível com o provisionamento, o gerenciamento de configurações e a implantação de aplicações. Desde o seu lançamento e posterior aquisição pela RedHat, ela continuou a crescer em popularidade. O NetApp fornece módulos certificados pelo Ansible que os clientes podem usar para automatizar a administração dos sistemas de storage da ONTAP. link:../additional/learn_more.html["Saiba mais"]Consulte e https://www.netapp.com/devops-solutions/ansible/["Soluções de DevOps do NetApp Ansible"^] para obter informações adicionais.

.Hub de automação do NetApp Console
O https://console.netapp.com/automationHub["Hub de automação do NetApp Console"^] Está disponível através da interface web do Console. O hub de automação fornece acesso a soluções prontas que podem ajudar você a automatizar a implantação e a integração do ONTAP com outros produtos. Ver https://docs.netapp.com/us-en/netapp-automation/["Automação da NetApp"^] Para obter documentação e mais informações.
