---
sidebar: sidebar 
permalink: rest/operational_characteristics.html 
keywords: rest, rest api, operation, request, response, crud 
summary: Embora O REST estabeleça um conjunto comum de tecnologias e práticas recomendadas, os detalhes de cada API podem variar com base nas escolhas de design. 
---
= Características operacionais da API REST do ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Embora O REST estabeleça um conjunto comum de tecnologias e práticas recomendadas, os detalhes de cada API podem variar com base nas escolhas de design.



== Transação de API de solicitação e resposta

Cada chamada de API REST é executada como uma solicitação HTTP para o sistema ONTAP, que gera uma resposta associada ao cliente. Esse par de solicitação/resposta é considerado uma transação de API. Antes de usar a API, você deve estar familiarizado com as variáveis de entrada disponíveis para controlar uma solicitação e o conteúdo da saída de resposta.



== Suporte para operações CRUD

Cada um dos recursos disponíveis por meio da API REST do ONTAP é acessado com base no modelo CRUD:

* Criar
* Leia
* Atualização
* Eliminar


Para alguns dos recursos, apenas um subconjunto das operações é suportado. Você deve revisar a página de documentação da API do ONTAP no cluster do ONTAP para obter mais informações sobre cada recurso.



== Identificadores de objeto

Cada instância ou objeto de recurso recebe um identificador exclusivo quando é criado. Na maioria dos casos, o identificador é um UUID de 128 bits. Esses identificadores são globalmente exclusivos dentro de um cluster ONTAP específico. Depois de emitir uma chamada de API que cria uma nova instância de objeto, um URL com o valor de id associado é retornado ao chamador no cabeçalho do local da resposta HTTP. Você pode extrair o identificador e usá-lo em chamadas subsequentes quando se refere à instância de recurso.


NOTE: O conteúdo e a estrutura interna dos identificadores de objeto podem mudar a qualquer momento. Você só deve usar os identificadores nas chamadas de API aplicáveis conforme necessário ao se referir aos objetos associados.



== Instâncias e coleções de objetos

Dependendo do caminho do recurso e do método HTTP, uma chamada de API pode ser aplicada a uma instância de objeto específica ou a uma coleção de objetos.



== Operações síncronas e assíncronas

Existem duas maneiras pelas quais o ONTAP executa uma solicitação HTTP recebida de um cliente.

Processamento síncrono:: O ONTAP executa a solicitação imediatamente e responde com um código de status HTTP de 200 ou 201 se for bem-sucedido.
+
--
Cada solicitação usando os métodos GET, HEAD e OPTIONS é sempre realizada de forma síncrona. Além disso, as solicitações que usam POST, PATCH e DELETE são projetadas para serem executadas de forma síncrona, se elas forem concluídas em menos de dois segundos.

--
Processamento assíncrono:: Se uma solicitação assíncrona for válida, o ONTAP criará uma tarefa em segundo plano para processar a solicitação e um objeto de tarefa para ancorar a tarefa. O status HTTP 202 é retornado ao chamador juntamente com o objeto da tarefa. Para determinar o sucesso ou falha final, você deve recuperar o estado do trabalho.
+
--
As solicitações que usam os métodos POST, PATCH e DELETE são projetadas para serem executadas assincronamente se forem esperadas levar mais de dois segundos para serem concluídas.


NOTE: O `return_timeout` parâmetro de consulta está disponível com chamadas assíncronas de API e pode converter uma chamada assíncrona para concluir de forma síncrona. link:../rest/asynchronous_processing.html["Processamento assíncrono usando o objeto Job"]Consulte para obter mais informações.

--




== Segurança

A segurança fornecida com a API REST é baseada principalmente nos recursos de segurança existentes disponíveis com o ONTAP. A seguinte segurança é usada pela API:

Segurança da camada de transporte:: Todo o tráfego enviado pela rede entre o cliente e o ONTAP LIF normalmente é criptografado usando TLS, com base nas configurações do ONTAP.
Autenticação de cliente:: As mesmas opções de autenticação disponíveis com o Gerenciador de sistema do ONTAP e o SDK de gerenciamento de rede também podem ser usadas com a API REST do ONTAP.
Autenticação HTTP:: Em um nível HTTP, por exemplo, ao acessar diretamente a API REST do ONTAP, há duas opções de autenticação conforme descrito abaixo. Em cada caso, você precisa criar um cabeçalho de autorização HTTP e incluí-lo em cada solicitação.
+
--
[cols="25,75"]
|===
| Opção | Descrição 


| Autenticação básica HTTP | O nome de usuário e a senha do ONTAP são concatenados com dois pontos. A cadeia de carateres é convertida para base64 e incluída no cabeçalho da solicitação. 


| OAuth 2,0 | A partir do ONTAP 9.14, você pode solicitar um token de acesso a um servidor de autorização externo e incluí-lo como um token de portador no cabeçalho da solicitação. 
|===
Para obter mais detalhes sobre o OAuth 2,0 e como ele é implementado no ONTAP, https://docs.netapp.com/us-en/ontap/authentication/overview-oauth2.html["Visão geral da implementação do ONTAP OAuth 2,0"^] consulte . Veja também link:../workflows/prepare_workflows.html["Prepare-se para usar os fluxos de trabalho"]abaixo neste site.

--
Autorização ONTAP:: O ONTAP implementa um modelo de autorização baseado em função. A conta que você usa ao acessar a API REST do ONTAP ou a página de documentação da API deve ter a autoridade adequada.

